version: '3'

services:

  postgres:
    image: "postgres:12"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: framework
      POSTGRES_PASSWORD: framework
      POSTGRES_DB: social_media

volumes:
  db_data: